#!/usr/bin/env python3
"""Checks and writes the Localizable.strings tables.

Keys are the German source strings found by l10n_keys.py; English comes from l10n_en.py. de.lproj gets identity
entries so German lookups never fall back to English. Exits 1 if a key lacks a translation, a translation is stale,
or format specifiers differ. Run with --write to regenerate Resources/Localization/{en,de}.lproj."""
import pathlib, re, sys
sys.path.insert(0, str(pathlib.Path(__file__).parent))
from l10n_keys import ROOT, keys
from l10n_en import EN

def specs(s): return re.findall(r'%(?:lld|@|d)', s)
def esc(s): return s.replace('\\', '\\\\').replace('"', '\\"')

found = keys()
problems = [f"missing English: {k!r} ({w})" for k, w in found.items() if k not in EN]
problems += [f"stale English: {k!r}" for k in EN if k not in found]
problems += [f"format mismatch: {k!r}" for k, v in EN.items() if specs(k) != specs(v)]
if '--write' in sys.argv:
    for lang, table in (('en', EN), ('de', {k: k for k in EN})):
        out = ROOT / 'Resources/Localization' / f'{lang}.lproj' / 'Localizable.strings'
        out.parent.mkdir(parents=True, exist_ok=True)
        body = ''.join(f'"{esc(k)}" = "{esc(v)}";\n' for k, v in sorted(table.items()) if k in found)
        out.write_text('/* Generated by scripts/l10n_check.py --write. Keys are the German source strings. */\n' + body)
print('\n'.join(problems) or f"OK: {len(found)} keys translated")
sys.exit(1 if problems else 0)
